---
- name: Detect services repository override directory
  local_action: 'stat path={{ services_repository_override }}'
  register: _repository_override

- name: Download services repository override directory
  copy:
      src: '{{ services_repository_override }}/'
      dest: /srv/services
  when: _repository_override.stat.exists == true
