---
- name: Stop formio container
  docker_service:
      project_src: /srv/formio
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: present
      stopped: yes
