---
- name: Stop cms container
  docker_service:
      project_src: /srv/cms
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: present
      stopped: yes
