---
- name: Configure authentication jwt key pass phrase
  lineinfile:
      path: '{{ authentication_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ authentication_jwt_key_pass_phrase }}'''
