---
- block:
      - name: Gather information for admin container
        include_tasks: /etc/ansible/task/app/proxy/container/info.yml
      - name: Define admin container variables
        set_fact:
            admin_env_file: .env.platform
        when: env == 'lab'
      - name: Define admin container variables
        set_fact:
            admin_compose_project_name: '{{ project }}_admin'
            admin_network: '{{ project }}proxy_default'
            admin_proxy_host: '{{ proxy_container_info_ip.stdout }}'
            admin_virtual_host: '{{ admin.host }}'
            admin_discovery_host: '{{ discovery.api.host }}'
            admin_directory: '{{ directory }}/admin'
      - name: Up admin container
        include_role:
            name: app/admin/container/up
  when: admin.enabled
  tags: [admin]
