---
- name: Configure cases jwt key pass phrase
  lineinfile:
      path: '{{ cases_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ cases_jwt_key_pass_phrase }}'''
