---
- name: Define authentication jwt variables
  set_fact:
      authentication_jwt_key_pass_phrase: '{{ jwt.pass_phrase }}'

- name: Configure authentication jwt key pass phrase
  include_role:
      name: app/authentication/jwt/configure
  when: authentication.enabled
  tags: [authentication]
