sudo: required

env:
  JWT_KEY_PASS_PHASE: 1111

services:
  - docker

before_install:
  - sudo openssl genrsa -out resource/jwt/test/ci/key -aes256 -passout pass:${JWT_KEY_PASS_PHASE} 4096
  - sudo openssl rsa -pubout -in resource/jwt/test/ci/key -out resource/jwt/test/ci/key.pub -passin pass:${JWT_KEY_PASS_PHASE}

script:
  - docker-compose up -d
  - docker-compose exec platform /bin/sh -c "cd /etc/ansible/env/test/ci && ansible-playbook ./install.yml"
  - docker-compose exec platform /bin/sh -c "cd /etc/ansible/env/test/ci && ansible-playbook ./test/validate.yml"
