---
- name: Define cases jwt variables
  set_fact:
      cases_jwt_key_pass_phrase: '{{ jwt.key_pass_phrase }}'

- name: Configure cases jwt key pass phrase
  include_role:
      name: app/cases/jwt/configure
  when: cases.enabled
  tags: [cases]
