---
- name: ...
  include_tasks: /etc/ansible/task/platform/compiler/find.yml
  vars:
      tag: repository

- name: ...
  set_fact:
      files: []

- name: ...
  include_tasks: /etc/ansible/task/platform/compiler/item.yml
  vars:
      tag: repository
      task: download
  with_items: '{{ items }}'
  when: vars[item|basename].enabled

- name: Completed
  debug:
      msg: Repository list has been compiled.
