---
- name: Define services jwt variables
  set_fact:
      services_jwt_key_pass_phrase: '{{ jwt.pass_phrase }}'

- name: Configure services jwt key pass phrase
  include_role:
      name: app/services/jwt/configure
  when: services.enabled
  tags: [services]
