---
- name: Down interactions container
  docker_service:
      project_src: /srv/interactions
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: absent
