---
- name: Configure records jwt key pass phrase
  lineinfile:
      path: '{{ records_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ records_jwt_key_pass_phrase }}'''
