---
- name: ...
  find:
      paths: /etc/ansible/task
      patterns: '.{{ tag }}'
      hidden: yes
      recurse: yes
  register: _result

- name: ...
  set_fact:
      _items: []

- name: ...
  set_fact:
      _items: '{{ _items }} + [ "{{ item.path|dirname }}" ]'
  with_items: '{{ _result.files }}'
  no_log: true
