---
- name: Configure topics jwt key pass phrase
  lineinfile:
      path: '{{ topics_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ topics_jwt_key_pass_phrase }}'''
