---
- name: Compile mail list
  hosts: platform
  become: true
  tasks:
    - name: ...
      include_tasks: /etc/ansible/task/platform/compiler/mail/configure.yml
  tags: [always]

- name: Configure mail settings
  hosts: server
  become: true
  tasks:
    - name: Include compiled list
      include_tasks: '{{ file }}'
      with_items: '{{ hostvars["platform"]["_files"] }}'
      loop_control:
        loop_var: file
