---
- name: Define records jwt variables
  set_fact:
      records_jwt_key_pass_phrase: '{{ jwt.pass_phrase }}'

- name: Configure records jwt key pass phrase
  include_role:
      name: app/records/jwt/configure
  when: records.enabled
  tags: [records]
