---
- name: Define services mail variables
  set_fact:
      services_mail_transport: '{{ mail.transport }}'
      services_mail_host: '{{ mail.host }}'
      services_mail_port: '{{ mail.port }}'
      services_mail_username: '{{ mail.username }}'
      services_mail_password: '{{ mail.password }}'

- name: Configure services mail settings
  include_role:
      name: app/services/mail/configure
  when: services.enabled
  tags: [services]
