---
- name: Backup interactions database migration file
  copy:
      src: '/srv/interactions/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/interactions/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ interactions_database_migration_data }}'
  when: interactions_database_migration_data is not none
  no_log: yes

- name: Create custom interactions database migration file
  copy:
      dest: '/srv/interactions/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      content: '{{ item.value|to_nice_yaml }}'
  with_dict: '{{ interactions_database_migration_data }}'
  when: interactions_database_migration_data is not none
  no_log: yes

- name: Load interactions database migration
  shell:
      cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ "" if interactions_database_migration_version is none else interactions_database_migration_version|replace(".", "_") }} --no-interaction | cat'
      chdir: /srv/interactions

# The restore backup task below runs before docker-compose above finishes executing. Look into fixing this.
- name: Pause while interactions database migration loads
  pause:
      seconds: 15

- name: Delete custom interactions database migration file
  file:
      path: '/srv/interactions/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ interactions_database_migration_data }}'
  when: interactions_database_migration_data is not none
  no_log: yes

- name: Restore interactions database migration file
  copy:
      src: '/srv/interactions/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/interactions/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ interactions_database_migration_data }}'
  when: interactions_database_migration_data is not none
  no_log: yes

- name: Remove backup interactions database migration file
  file:
      path: '/srv/interactions/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ interactions_database_migration_data }}'
  when: interactions_database_migration_data is not none
  no_log: yes
