---
- name: Detect monitor repository override directory
  local_action: 'stat path={{ monitor_repository_override }}'
  register: repository_override

- name: Download monitor repository override directory
  copy:
      src: '{{ monitor_repository_override }}/'
      dest: /srv/monitor
  when: repository_override.stat.exists == true
