---
- block:
      - name: Gather information for identities container
        include_tasks: /etc/ansible/task/app/proxy/container/info.yml
      - name: Define identities container variables
        set_fact:
            identities_env_file: .env.lab
        when: env == 'lab'
      - name: Define identities container variables
        set_fact:
            identities_compose_project_name: '{{ project }}identities'
            identities_network: '{{ project }}proxy_default'
            identities_proxy_host: '{{ proxy_container_info_ip.stdout }}'
            identities_nginx_virtual_host: '{{ identities.api.host }}'
            identities_adminer_virtual_host: '{{ identities.adminer.host }}'
            identities_discovery_host: '{{ discovery.api.host }}'
            identities_directory: '{{ directory }}/identities'
            identities_database_host: '{{ identities.database.host }}'
            identities_database_port: '{{ identities.database.port }}'
            identities_database_name: '{{ identities.database.name }}'
            identities_database_username: '{{ identities.database.username }}'
            identities_database_password: '{{ identities.database.password }}'
      - name: Up identities container
        include_role:
            name: app/identities/container/up
  when: identities.enabled
  tags: [identities]
