---
- name: Detect ui repository override directory
  local_action: 'stat path={{ ui_repository_override }}'
  register: repository_override

- name: Download ui repository override directory
  copy:
      src: '{{ ui_repository_override }}/'
      dest: /srv/ui
  when: repository_override.stat.exists == true
