---
- name: Download authentication jwt private key
  copy:
      src: '{{ jwt_private_key }}'
      dest: /srv/authentication/var/jwt/key
      mode: 0600

- name: Download authentication jwt public key
  copy:
      src: '{{ jwt_public_key }}'
      dest: /srv/authentication/var/jwt/key.pub
      mode: 0600
