---
- block:
      - name: Gather information for services container
        include_tasks: /etc/ansible/task/app/proxy/container/info.yml
      - name: Define services container variables
        set_fact:
            services_env_file: .env.lab
        when: env == 'lab'
      - name: Define services container variables
        set_fact:
            services_compose_project_name: '{{ project }}services'
            services_network: '{{ project }}proxy_default'
            services_proxy_host: '{{ proxy_container_info_ip.stdout }}'
            services_nginx_virtual_host: '{{ services.api.host }}'
            services_adminer_virtual_host: '{{ services.adminer.host }}'
            services_discovery_host: '{{ discovery.api.host }}'
            services_directory: '{{ directory }}/services'
            services_database_host: '{{ services.database.host }}'
            services_database_port: '{{ services.database.port }}'
            services_database_name: '{{ services.database.name }}'
            services_database_username: '{{ services.database.username }}'
            services_database_password: '{{ services.database.password }}'
      - name: Up services container
        include_role:
            name: app/services/container/up
  when: services.enabled
  tags: [services]
