---
- name: Configure interactions jwt key pass phrase
  lineinfile:
      path: '{{ interactions_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ interactions_jwt_key_pass_phrase }}'''
