---
- name: ...
  include_tasks: /etc/ansible/task/platform/compiler/find.yml
  vars:
      tag: encryption

- name: ...
  set_fact:
      files: []

- name: ...
  include_tasks: /etc/ansible/task/platform/compiler/item.yml
  vars:
      tag: encryption
      task: configure
  with_items: '{{ items }}'
  when: vars[item|basename].enabled

- name: Completed
  debug:
      msg: Encryption list has been compiled.
