---
- name: Detect documentation repository override directory
  local_action: 'stat path={{ documentation_repository_override }}'
  register: repository_override

- name: Download documentation repository override directory
  copy:
      src: '{{ documentation_repository_override }}/'
      dest: /srv/documentation
  when: repository_override.stat.exists == true
