---
- name: Define topics mail variables
  set_fact:
      topics_mail_transport: '{{ mail.transport }}'
      topics_mail_host: '{{ mail.host }}'
      topics_mail_port: '{{ mail.port }}'
      topics_mail_username: '{{ mail.username }}'
      topics_mail_password: '{{ mail.password }}'

- name: Configure topics mail settings
  include_role:
      name: app/topics/mail/configure
  when: topics.enabled
  tags: [topics]
