---
- name: Define tasks jwt variables
  set_fact:
      tasks_jwt_key_pass_phrase: '{{ jwt.key_pass_phrase }}'

- name: Configure tasks jwt key pass phrase
  include_role:
      name: app/tasks/jwt/configure
  when: tasks.enabled
  tags: [tasks]
