---
- name: Define interactions jwt variables
  set_fact:
      interactions_jwt_key_pass_phrase: '{{ jwt.key_pass_phrase }}'

- name: Configure interactions jwt key pass phrase
  include_role:
      name: app/interactions/jwt/configure
  when: interactions.enabled
  tags: [interactions]
