---
- name: Stop records container
  docker_service:
      project_src: /srv/records
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: present
      stopped: yes
