---
- block:
    - name: Define discovery map variable
      set_fact:
          discovery_map:
              assets: '{{ assets.api.host }}'
              authentication: '{{ authentication.api.host }}'
              camunda: '{{ camunda.api.host }}/engine-rest'
              cases: '{{ cases.api.host }}'
              cms: '{{ cms.api.host }}'
              discovery: '{{ discovery.api.host }}'
              formio: '{{ formio.api.host }}'
              identities: '{{ identities.api.host }}'
              interactions: '{{ interactions.api.host }}'
              logs: '{{ logs.api.host }}'
              records: '{{ records.api.host }}'
              services: '{{ services.api.host }}'
              tasks: '{{ tasks.api.host }}'
              topics: '{{ topics.api.host }}'
    - name: Set discovery map
      include_role:
          name: app/discovery/map/configure
  when: discovery.enabled
  tags: [discovery]
