---
- name: Detect authentication repository override directory
  local_action: 'stat path={{ authentication_repository_override }}'
  register: repository_override

- name: Download authentication repository override directory
  copy:
      src: '{{ authentication_repository_override }}/'
      dest: /srv/authentication
  when: repository_override.stat.exists == true
