---
- name: Detect formio repository override directory
  local_action: 'stat path={{ formio_repository_override }}'
  register: repository_override

- name: Download formio repository override directory
  copy:
      src: '{{ formio_repository_override }}/'
      dest: /srv/formio
  when: repository_override.stat.exists == true
