---
- name: Configure identities jwt key pass phrase
  lineinfile:
      path: '{{ identities_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ identities_jwt_key_pass_phrase }}'''
