---
- name: Compile encryption list
  hosts: platform
  become: true
  tasks:
    - name: ...
      include_tasks: /etc/ansible/task/platform/compiler/encryption/configure.yml
  tags: [always]

- name: Configure encryption settings
  hosts: server
  become: true
  tasks:
    - name: Include compiled list
      include_tasks: '{{ file }}'
      with_items: '{{ hostvars["platform"]["_files"] }}'
      loop_control:
        loop_var: file
