---
- name: Define identities discovery variables
  set_fact:
      identities_discovery_host: '{{ discovery.api.host }}'

- name: Configure identities discovery settings
  include_role:
      name: app/identities/discovery/configure
  when: identities.enabled
  tags: [identities]
