---
- name: Define cms jwt variables
  set_fact:
      cms_jwt_key_pass_phrase: '{{ jwt.key_pass_phrase }}'

- name: Configure cms jwt key pass phrase
  include_role:
      name: app/cms/jwt/configure
  when: cms.enabled
  tags: [cms]
