---
- name: Configure tasks mail transport setting
  lineinfile:
      path: '{{ tasks_mail_config_file }}'
      regexp: '^\s{4}mailer_transport:'
      line: '    mailer_transport: {{ tasks_mail_transport }}'

- name: Configure tasks mail host setting
  lineinfile:
      path: '{{ tasks_mail_config_file }}'
      regexp: '^\s{4}mailer_host:'
      line: '    mailer_host: {{ tasks_mail_host }}'

- name: Configure tasks mail port setting
  lineinfile:
      path: '{{ tasks_mail_config_file }}'
      regexp: '^\s{4}mailer_port:'
      line: '    mailer_port: {{ tasks_mail_port }}'

- name: Configure tasks mail username setting
  lineinfile:
      path: '{{ tasks_mail_config_file }}'
      regexp: '^\s{4}mailer_user:'
      line: '    mailer_user: {{ tasks_mail_username }}'

- name: Configure tasks mail password setting
  lineinfile:
      path: '{{ tasks_mail_config_file }}'
      regexp: '^\s{4}mailer_password:'
      line: '    mailer_password: ''{{ tasks_mail_password }}'''
