---
- name: Download topics jwt private key
  copy:
      src: '{{ jwt_private_key }}'
      dest: /srv/topics/var/jwt/key
      mode: 0600

- name: Download topics jwt public key
  copy:
      src: '{{ jwt_public_key }}'
      dest: /srv/topics/var/jwt/key.pub
      mode: 0600
