---
- name: Detect topics repository override directory
  local_action: 'stat path={{ topics_repository_override }}'
  register: repository_override

- name: Download topics repository override directory
  copy:
      src: '{{ topics_repository_override }}/'
      dest: /srv/topics
  when: repository_override.stat.exists == true
