---
- name: Configure tasks jwt key pass phrase
  lineinfile:
      path: '{{ tasks_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ tasks_jwt_key_pass_phrase }}'''
