---
- name: Define identities encryption variables
  set_fact:
      identities_encryption_secret: '{{ encryption.secret }}'

- name: Configure identities encryption settings
  include_role:
      name: app/identities/encryption/configure
  when: identities.enabled
  tags: [identities]
