---
- name: Download assets jwt private key
  copy:
      src: '{{ jwt_private_key }}'
      dest: /srv/assets/var/jwt/key
      mode: 0600

- name: Download assets jwt public key
  copy:
      src: '{{ jwt_public_key }}'
      dest: /srv/assets/var/jwt/key.pub
      mode: 0600
