---
- block:
    - name: Define tasks config variables
      set_fact:
          tasks_config: '{{ config }}'
    - name: Set tasks configs
      include_role:
          name: app/tasks/config/set
  when: tasks.enabled
  tags: [tasks]
