---
- name: Stop services container
  docker_service:
      project_src: /srv/services
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: present
      stopped: yes
