---
- name: Detect tasks repository override directory
  local_action: 'stat path={{ tasks_repository_override }}'
  register: _repository_override

- name: Download tasks repository override directory
  copy:
      src: '{{ tasks_repository_override }}/'
      dest: /srv/tasks
  when: _repository_override.stat.exists == true
