---
- block:
    - name: Define cms config variables
      set_fact:
          cms_config: '{{ config }}'
    - name: Set cms configs
      include_role:
          name: app/cms/config/set
  when: cms.enabled
  tags: [cms]
