---
- name: Detect interactions repository override directory
  local_action: 'stat path={{ interactions_repository_override }}'
  register: repository_override

- name: Download interactions repository override directory
  copy:
      src: '{{ interactions_repository_override }}/'
      dest: /srv/interactions
  when: repository_override.stat.exists == true
