---
- name: Configure cms jwt key pass phrase
  lineinfile:
      path: '{{ cms_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ cms_jwt_key_pass_phrase }}'''
