---
- name: Backup records database migration file
  copy:
      src: '/srv/records/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/records/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ records_database_migration_data }}'
  when: records_database_migration_data is not none
  no_log: yes

- name: Create custom records database migration file
  copy:
      dest: '/srv/records/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      content: '{{ item.value|to_nice_yaml }}'
  with_dict: '{{ records_database_migration_data }}'
  when: records_database_migration_data is not none
  no_log: yes

- name: Load records database migration
  shell:
      cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ "" if records_database_migration_version is none else records_database_migration_version|replace(".", "_") }} --no-interaction | cat'
      chdir: /srv/records

# The restore backup task below runs before docker-compose above finishes executing. Look into fixing this.
- name: Pause while records database migration loads
  pause:
      seconds: 15

- name: Delete custom records database migration file
  file:
      path: '/srv/records/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ records_database_migration_data }}'
  when: records_database_migration_data is not none
  no_log: yes

- name: Restore records database migration file
  copy:
      src: '/srv/records/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/records/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ records_database_migration_data }}'
  when: records_database_migration_data is not none
  no_log: yes

- name: Remove backup records database migration file
  file:
      path: '/srv/records/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ records_database_migration_data }}'
  when: records_database_migration_data is not none
  no_log: yes
