---
- name: Detect proxy repository override directory
  local_action: 'stat path={{ proxy_repository_override }}'
  register: _repository_override

- name: Download proxy repository override directory
  copy:
      src: '{{ proxy_repository_override }}/'
      dest: /srv/proxy
  when: _repository_override.stat.exists == true
