---
- name: Detect records repository override directory
  local_action: 'stat path={{ records_repository_override }}'
  register: repository_override

- name: Download records repository override directory
  copy:
      src: '{{ records_repository_override }}/'
      dest: /srv/records
  when: repository_override.stat.exists == true
