---
- name: Stop cases container
  docker_service:
      project_src: /srv/cases
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: present
      stopped: yes
