---
- name: Backup topics database migration file
  copy:
      src: '/srv/topics/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/topics/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ topics_database_migration_data }}'
  when: topics_database_migration_data is not none
  no_log: yes

- name: Create custom topics database migration file
  copy:
      dest: '/srv/topics/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      content: '{{ item.value|to_nice_yaml }}'
  with_dict: '{{ topics_database_migration_data }}'
  when: topics_database_migration_data is not none
  no_log: yes

- name: Load topics database migration
  shell:
      cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ "" if topics_database_migration_version is none else topics_database_migration_version|replace(".", "_") }} --no-interaction | cat'
      chdir: /srv/topics

# The restore backup task below runs before docker-compose above finishes executing. Look into fixing this.
- name: Pause while topics database migration loads
  pause:
      seconds: 15

- name: Delete custom topics database migration file
  file:
      path: '/srv/topics/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ topics_database_migration_data }}'
  when: topics_database_migration_data is not none
  no_log: yes

- name: Restore topics database migration file
  copy:
      src: '/srv/topics/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/topics/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ topics_database_migration_data }}'
  when: topics_database_migration_data is not none
  no_log: yes

- name: Remove backup topics database migration file
  file:
      path: '/srv/topics/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ topics_database_migration_data }}'
  when: topics_database_migration_data is not none
  no_log: yes
