---
- name: Define records discovery variables
  set_fact:
      records_discovery_host: '{{ discovery.api.host }}'

- name: Configure records discovery settings
  include_role:
      name: app/records/discovery/configure
  when: records.enabled
  tags: [records]
