---
- block:
      - name: Gather information for monitor container
        include_tasks: /etc/ansible/task/app/proxy/container/info.yml
      - name: Define monitor container variables
        set_fact:
            monitor_env_file: .env.platform
        when: env == 'lab'
      - name: Define monitor container variables
        set_fact:
            monitor_compose_project_name: '{{ project }}_monitor'
            monitor_network: '{{ project }}proxy_default'
            monitor_proxy_host: '{{ proxy_container_info_ip.stdout }}'
            monitor_virtual_host: '{{ monitor.host }}'
            monitor_discovery_host: '{{ discovery.api.host }}'
            monitor_directory: '{{ directory }}/monitor'
      - name: Up monitor container
        include_role:
            name: app/monitor/container/up
  when: monitor.enabled
  tags: [monitor]
