---
- name: Backup authentication database migration file
  copy:
      src: '/srv/authentication/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/authentication/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ authentication_database_migration_data }}'
  when: authentication_database_migration_data is not none
  no_log: yes

- name: Create custom authentication database migration file
  copy:
      dest: '/srv/authentication/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      content: '{{ item.value|to_nice_yaml }}'
  with_dict: '{{ authentication_database_migration_data }}'
  when: authentication_database_migration_data is not none
  no_log: yes

- name: Load authentication database migration
  shell:
      cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ "" if authentication_database_migration_version is none else authentication_database_migration_version|replace(".", "_") }} --no-interaction | cat'
      chdir: /srv/authentication

# The restore backup task below runs before docker-compose above finishes executing. Look into fixing this.
- name: Pause while authentication database migration loads
  pause:
      seconds: 15

- name: Delete custom authentication database migration file
  file:
      path: '/srv/authentication/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ authentication_database_migration_data }}'
  when: authentication_database_migration_data is not none
  no_log: yes

- name: Restore authentication database migration file
  copy:
      src: '/srv/authentication/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/authentication/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ authentication_database_migration_data }}'
  when: authentication_database_migration_data is not none
  no_log: yes

- name: Remove backup authentication database migration file
  file:
      path: '/srv/authentication/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ authentication_database_migration_data }}'
  when: authentication_database_migration_data is not none
  no_log: yes
