---
- name: Detect identities repository override directory
  local_action: 'stat path={{ identities_repository_override }}'
  register: repository_override

- name: Download identities repository override directory
  copy:
      src: '{{ identities_repository_override }}/'
      dest: /srv/identities
  when: repository_override.stat.exists == true
