---
- name: Backup tasks database migration file
  copy:
      src: '/srv/tasks/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/tasks/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ tasks_database_migration_data }}'
  when: tasks_database_migration_data is not none
  no_log: yes

- name: Create custom tasks database migration file
  copy:
      dest: '/srv/tasks/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      content: '{{ item.value|to_nice_yaml }}'
  with_dict: '{{ tasks_database_migration_data }}'
  when: tasks_database_migration_data is not none
  no_log: yes

- name: Load tasks database migration
  shell:
      cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ "" if tasks_database_migration_version is none else tasks_database_migration_version|replace(".", "_") }} --no-interaction | cat'
      chdir: /srv/tasks

# The restore backup task below runs before docker-compose above finishes executing. Look into fixing this.
- name: Pause while tasks database migration loads
  pause:
      seconds: 15

- name: Delete custom tasks database migration file
  file:
      path: '/srv/tasks/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ tasks_database_migration_data }}'
  when: tasks_database_migration_data is not none
  no_log: yes

- name: Restore tasks database migration file
  copy:
      src: '/srv/tasks/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      remote_src: yes
      dest: '/srv/tasks/src/AppBundle/Resources/migrations/{{ item.key|replace(".", "_") }}.yml'
  with_dict: '{{ tasks_database_migration_data }}'
  when: tasks_database_migration_data is not none
  no_log: yes

- name: Remove backup tasks database migration file
  file:
      path: '/srv/tasks/src/AppBundle/Resources/migrations/_{{ item.key|replace(".", "_") }}.yml'
      state: absent
  with_dict: '{{ tasks_database_migration_data }}'
  when: tasks_database_migration_data is not none
  no_log: yes
