---
identities_env_file: ~
identities_compose_project_name: dsidentities
identities_network: dsproxy_default
identities_proxy_host: 127.0.0.1
identities_nginx_virtual_host: api.identities.ds
identities_adminer_virtual_host: adminer.identities.ds
identities_discovery_host: api.discovery.ds
identities_directory: /srv/identities
identities_database_host: identities_db
identities_database_port: 5432
identities_database_name: identities
identities_database_username: identities
identities_database_password: identities
