---
- name: Down authentication container
  docker_service:
      project_src: /srv/authentication
      files:
          - docker-compose.yml
          - 'docker-compose.{{ env }}.yml'
      state: absent
