---
- name: Compile discovery list
  hosts: platform
  become: true
  tasks:
    - name: ...
      include_tasks: /etc/ansible/task/platform/compiler/discovery/configure.yml
  tags: [always]

- name: Configure discovery settings
  hosts: server
  become: true
  tasks:
    - name: Include compiled list
      include_tasks: '{{ file }}'
      with_items: '{{ hostvars["platform"]["_files"] }}'
      loop_control:
        loop_var: file

- name: Configure discovery settings
  hosts: server
  become: true
  tasks:
    - name: Configure discovery domain mapping
      include_tasks: /etc/ansible/task/app/discovery/map/configure.yml
