---
- name: Configure interactions encryption secret setting
  lineinfile:
      path: '{{ interactions_encryption_config_file }}'
      regexp: '^\s{4}secret:'
      line: '    secret: {{ interactions_encryption_secret }}'
