---
- name: Detect guide repository override directory
  local_action: 'stat path={{ guide_repository_override }}'
  register: _repository_override

- name: Download guide repository override directory
  copy:
      src: '{{ guide_repository_override }}/'
      dest: /srv/guide
  when: _repository_override.stat.exists == true
