---
- name: Download tasks jwt private key
  copy:
      src: '{{ jwt_private_key }}'
      dest: /srv/tasks/var/jwt/key
      mode: 0600

- name: Download tasks jwt public key
  copy:
      src: '{{ jwt_public_key }}'
      dest: /srv/tasks/var/jwt/key.pub
      mode: 0600
