---
- block:
      - name: Gather information for portal container
        include_tasks: /etc/ansible/task/app/proxy/container/info.yml
      - name: Define portal container variables
        set_fact:
            portal_env_file: .env.platform
        when: env == 'lab'
      - name: Define portal container variables
        set_fact:
            portal_compose_project_name: '{{ project }}_portal'
            portal_network: '{{ project }}proxy_default'
            portal_proxy_host: '{{ proxy_container_info_ip.stdout }}'
            portal_virtual_host: '{{ portal.host }}'
            portal_discovery_host: '{{ discovery.api.host }}'
            portal_directory: '{{ directory }}/portal'
      - name: Up portal container
        include_role:
            name: app/portal/container/up
  when: portal.enabled
  tags: [portal]
