---
- name: Detect core repository override directory
  local_action: 'stat path={{ core_repository_override }}'
  register: _repository_override

- name: Download core repository override directory
  copy:
      src: '{{ core_repository_override }}/'
      dest: /srv/core
  when: _repository_override.stat.exists == true
