---
- name: Configure cases encryption secret setting
  lineinfile:
      path: '{{ cases_encryption_config_file }}'
      regexp: '^\s{4}secret:'
      line: '    secret: {{ cases_encryption_secret }}'
