---
cases_env_file: ~
cases_compose_project_name: dscases
cases_network: dsproxy_default
cases_proxy_host: 127.0.0.1
cases_nginx_virtual_host: api.cases.ds
cases_adminer_virtual_host: adminer.cases.ds
cases_discovery_host: api.discovery.ds
cases_directory: /srv/cases
cases_database_host: cases_db
cases_database_port: 5432
cases_database_name: cases
cases_database_username: cases
cases_database_password: cases
