---
- name: Configure assets jwt key pass phrase
  lineinfile:
      path: '{{ assets_config_file }}'
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ assets_jwt_key_pass_phrase }}'''
